I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 47, in script
    python:
  File "game/script.rpy", line 47, in script
    python:
  File "game/script.rpy", line 50, in <module>
    renpy.say(e,"You have [config]")
  File "renpy/common/00nvl_mode.rpy", line 537, in _nvl_adv_callback
    if config.adv_nvl_transition:
AttributeError: 'unicode' object has no attribute 'adv_nvl_transition'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/opt/renpy/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/opt/renpy/renpy/main.py", line 652, in main
    run(restart)
  File "/opt/renpy/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/opt/renpy/renpy/execution.py", line 922, in run_context
    context.run()
  File "game/script.rpy", line 47, in script
    python:
  File "game/script.rpy", line 47, in script
    python:
  File "/opt/renpy/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/opt/renpy/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 50, in <module>
    renpy.say(e,"You have [config]")
  File "/opt/renpy/renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "/opt/renpy/renpy/character.py", line 1210, in __call__
    renpy.exports.mode(mode)
  File "/opt/renpy/renpy/exports.py", line 3232, in mode
    c(mode, modes)
  File "renpy/common/00nvl_mode.rpy", line 537, in _nvl_adv_callback
    if config.adv_nvl_transition:
AttributeError: 'unicode' object has no attribute 'adv_nvl_transition'

Linux-5.17.5-76051705-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.10.2178
Lovu Lovu Learning 1.0
Wed Jul 27 19:10:29 2022
